Update docker-deploy.yml

diff --git a/.github/workflows/docker-deploy.yml b/.github/workflows/docker-deploy.yml
--- a/.github/workflows/docker-deploy.yml
+++ b/.github/workflows/docker-deploy.yml
@@ -52,6 +52,12 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           password: ${{ secrets.SERVER_PASSWORD }}
           script: |
+            echo "$APP_SECRETS" > /tmp/app_secrets.json
+            if [ ! -f /tmp/app_secrets.json ]; then
+              echo ".env file not found"
+              exit 1
+            fi
+            jq -r 'to_entries[] | "\(.key)=\(.value)"' /tmp/app_secrets.json > /tmp/.env
             set -a
             source .env
             set +a
